app_hooks/urls.py
from django.urls import path
from .views import (EventViewSet, EventListView, MakeDirectEndpoint,
                    MakeEmbededEndpoint, MakeEvent, MakeFields, MakeFilter, MakeFooter,
                    EventDeleteView, EventUpdateView)
from django.contrib.auth.decorators import login_required

app_name = 'events'

urlpatterns = [
    path('jira-callback/', EventViewSet.as_view(), name='jira-callback'),
    path('events/', login_required(EventListView.as_view()), name='events'),
    path('make_eventdirect/',
         login_required(MakeDirectEndpoint.as_view()), name='make_eventdirect'),
    path('make_eventembed/', login_required(MakeEmbededEndpoint.as_view()),
         name='make_eventembed'),
    path('make_event/', login_required(MakeEvent.as_view()),
         name='make_event'),
    path('make_fields/', login_required(MakeFields.as_view()),
         name='make_fields'),
    path('make_filter/', login_required(MakeFilter.as_view()),
         name='make_filter'),
    path('make_footer/', login_required(MakeFooter.as_view()),
         name='make_footer'),
    path('events/<int:pk>/delete', login_required(EventDeleteView.as_view()),
         name='del_events'),
    path('events/<int:pk>/update', login_required(EventUpdateView.as_view()),
         name='upd_events'),

]

app_users/urls.py
from django.urls import path
from .views import LoginUser
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

proj_webhook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_hooks.urls')),
    path('users/', include('app_users.urls', namespace='users_log')),
    path('accounts/', include('app_users.urls')),
]

app_users/models.py
from django.db import models

# Create your models here.

app_users/forms.py
from django import forms
from app_hooks.models import (Filter, EmbededFooter, EmbededFields,
                              EndpointDirect, EndpointEmbeded, Event,
                              MiddlewaresBase)
from django.contrib.auth.forms import AuthenticationForm

from django.forms import inlineformset_factory


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите логин'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Введите пароль'}))


class FilterForm(forms.ModelForm):
    class Meta:
        model = Filter
        fields = ['name', 'data']
        labels = {
            'name': 'Введите название фильтра',
            'data': 'Введите данные фильтра',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'data': forms.Textarea(attrs={'class': 'form-control', 'rows': 5})
        }


class EndpointDirectForm(forms.ModelForm):
    class Meta:
        model = EndpointDirect
        fields = ['name', 'callback', 'template']
        labels = {
            'name': 'Введите название эндпоинта',
            'callback': 'Введите данные callback(url)',
            'template': 'Введите данные template'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'callback': forms.TextInput(attrs={'class': 'form-control'}),
            'template': forms.Textarea(attrs={'class': 'form-control'})
        }


class EmbededFieldsForm(forms.ModelForm):
    class Meta:
        model = EmbededFields
        fields = ['name', 'value', 'inline']
        labels = {
            'name': 'Введите название доп. поля',
            'value': 'Введите данные доп. поля',
            'inline': 'Выберите Inline'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'value': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EmbededFooterForm(forms.ModelForm):
    class Meta:
        model = EmbededFooter
        fields = ['text', 'icon_url']
        labels = {
            'text': 'Введите текст футера',
            'icon_url': 'Введите ссылку на изображение футера'
        }
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
            'icon_url': forms.TextInput(attrs={'class': 'form-control'})
        }


class EndpointEmbededForm(forms.ModelForm):

    class Meta:
        model = EndpointEmbeded
        fields = ['name', 'callback', 'title', 'description',
                  'url', 'color', 'thumbnail', 'author', 'fields', 'footer']
        labels = {
            'name': 'Введите название эндпоинта',
            'callback': 'Введите данные callback(url)',
            'title': 'Введите данные title',
            'description': 'Введите данные description',
            'url': 'Введите URL',
            'color': 'Введите цвет в формате цифр',
            'thumbnail': 'Введите данные thumbnail(url)',
            'author': 'Введите автора',
            'fields': 'Выберите fields или добавьте новый',
            'footer': 'Выберите footer или добавьте новый'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'callback': forms.TextInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'}),
            'color': forms.TextInput(attrs={'class': 'form-control'}),
            'thumbnail': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'fields': forms.SelectMultiple(attrs={'class': 'form-select'}),
            'footer': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'filters', 'endpoints']
        labels = {
            'name': 'Введите название Ивента',
            'filters': 'Выберите фильтр из списка или добавьте новый',
            'endpoints': 'Выберите эндпоинт из списка или добавьте новый'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'filters': forms.SelectMultiple(attrs={'class': 'form-select'}),
            'endpoints': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }


class MiddlewareForm(forms.ModelForm):
    class Meta:
        model = MiddlewaresBase
        fields = ['type']
        labels = {
            'type': 'Выберите Middleware'
        }
        widgets = {
            'type': forms.Select(attrs={'class': 'form-select'})
        }

app_users/views.py
from .forms import LoginUserForm
from django.contrib.auth.views import LoginView
from .forms import LoginUserForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'app_users/login.html'

app_users/templates/app_users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Events{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&display=swap">
</head>
<body>
    <div class="container p-3 my-5 text-black" style="background-color: #ffc107; color: black; display: flex; align-items: center; justify-content: space-between;">
        <div>
            <img src="{% static "logo_clean_2x-removebg-preview.png" %}" alt="Logo" class="d-inline-block align-items-center">Система создания Ивентов
        </div>
        <nav class="navbar navbar-expand-sm bg-black">
            <div class="container-fluid">
                <!-- Links -->
                <ul class="navbar-nav">
                    
                    {% if request.user.is_authenticated %}
                        <li class="nav-item" style="margin-right: 10px;">
                            <a class="nav-link border rounded-pill" href="/events" style="color: black;">Созданные Ивенты</a>
                        </li>
                        <li class="nav-item" style="margin-right: 10px;">
                            <a class="nav-link border rounded-pill" href="/make_event" style="color: black;">Создать Ивент</a>
                        </li>
                        <li class="nav-item" style="margin-right: 10px;">
                            <a class="nav-link border rounded-pill" href="/users/logout" style="color: black;">Выход</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        <div class="d-flex justify-content-end">
            {% if request.user.is_authenticated %}
                <p class="me-3">Пользователь: {{ request.user.username }}</p>
            {% endif %}
        </div>
        {% if messages %}
        <div class="mt-3">
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        {% block login_form %}{% endblock %}
        {% block all_events %}{% endblock %}
    </div>
    <!-- Bootstrap JS and Popper.js (required for Bootstrap) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app_users/templates/app_users/content_update.html
{% load crispy_forms_tags %}
{% load helper_tags %}
{% block content %}
  <h1>Пожалуйста, внесите изменения: </h1>   
  <div class="col-8 my-4">
    <p class="h1 mb-0">СТАТУС: {% if form.instance.draft %}<span class="text-success">ОПУБЛИКОВАН</span>{% else %}<span class="text-warning">ЧЕРНОВИК</span>{% endif %}</p>
  </div>
  <form method="post" action="{% url 'events:upd_events' pk=event_id %}">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" name="notpub_button" class="btn btn-outline-warning">Сохранить как черновик</button>
    <button type="submit" name="pub_button" class="btn btn-outline-success">Сохранить для публикации</button>
  </form>
{% endblock %}

app_users/templates/app_users/embededfields.html
{% load crispy_forms_tags %}
{% block fields_form_content %}
<h2>Заполните форму для добавления Fields</h2>
<form method="post">
  <div class="mb-3">
    <div class="form-control">
      {% csrf_token %} {{embededfields_form|crispy}}
    </div>
  </div>
  <button type="submit" class="btn btn-outline-warning">Сохранить Field</button>
</form>
{% endblock %}

app_users/templates/app_users/embededfooter.html
{% load crispy_forms_tags %}
{% block footer_form_content %}
    <h2>Заполните форму для добавления Footer</h2>
    <form method="post">
        <div class="mb-3">
            <div class="form-control">
                {% csrf_token %}
                {{footer_form|crispy}}
            </div>
        </div>
        <button type="submit" class="btn btn-outline-warning">Сохранить Footer</button>
    </form>
{% endblock %}

app_users/templates/app_users/endpointdirect.html
{% load crispy_forms_tags %}
{% block direct_form_content %}
  <h2>Заполните форму для добавления endpoint_direct</h2>
  <form method="post">
    <div class="col-md-8">
      {% csrf_token %}
      {{ direct_form|crispy }}
    </div>
    <div class="col-md-8">
      {% csrf_token %}
      {{ middleware_form|crispy }}
    </div>
    <button type="submit" class="btn btn-outline-warning">Сохранить Endpoint</button>
  </form>
{% endblock %}

app_users/templates/app_users/endpointembeded.html
{% load crispy_forms_tags %} {% block embeded_form_content %}
<h2>Заполните форму для добавления endpoint_embeded</h2>
<form method="post" action="{% url 'events:make_eventembed' %}" class="row g-3">
  {% csrf_token %}
  <div class="col-md-8">
    {{ embeded_form|crispy }}
    {{ middleware_form|crispy }}
  </div>
  <div class="col-md-4">
    <div class="form-group">
      <a href="{% url 'events:make_fields' %}" class="btn btn-outline-warning" style="margin-top: 720px;">Добавить fields</a>
      <a href="{% url 'events:make_footer' %}" class="btn btn-outline-warning" style="margin-top: 98px;">Добавить footer</a>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-outline-warning">Сохранить Endpoint</button>
  </div>
</form>
{% endblock %}

app_users/templates/app_users/event.html
{% load crispy_forms_tags %} {% block event_form_content %}
<h2>Заполните форму для добавления Event</h2>
<form method="post" action="{% url 'events:make_event' %}" class="row g-3">
  {% csrf_token %}
  <div class="col-md-8">
    {{ event_form.as_p }}
  </div>
  
  <div class="col-md-4">
    <div class="form-group">
      <a href="{% url 'events:make_filter' %}" class="btn btn-outline-warning" style="margin-top: 126px;">Добавить новый фильтр</a>
    </div>
    
    <div class="form-group">
      <a href="{% url 'events:make_eventdirect' %}" class="btn btn-outline-warning" style="margin-top: 91px;">Добавить direct</a>
      <a href="{% url 'events:make_eventembed' %}" class="btn btn-outline-warning" style="margin-top: 10px;">Добавить embed</a>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-outline-warning">Сохранить Event</button>
  </div>
</form>
{% endblock %}

app_users/templates/app_users/filter.html
{% load crispy_forms_tags %} {% block filter_form_content %}
<h2>Заполните форму для добавления Filter</h2>
<form method="post">
  <div class="mb-3">
    <div class="form-control">{% csrf_token %} {{filter_form|crispy}}</div>
  </div>
  <button type="submit" class="btn btn-outline-warning">Сохранить Filter</button>
</form>
{% endblock %}

app_users/templates/app_users/login.html
{% extends "app_users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Авторизация{% endblock %}

{% block login_form %}
    <form method="post">
        <div class="center-block">
            {% csrf_token %}
            {{form|crispy}}
        <button type="submit" class="btn btn-outline-warning">Войти</button>
    </form>
    </div>
{% endblock %}

app_users/templates/app_users/middleware.html
{% load crispy_forms_tags %}
{% block middleware_form_content %}
<form method="post">
  <div class="mb-3">
    <div class="form-control">
        {% csrf_token %}
        {{middleware_form|crispy}}</div>
  </div>
  <button type="submit" class="btn btn-outline-warning">Сохранить Middleware</button>
</form>
{% endblock %}