app_hooks/urls.py
from django.urls import path
from .views import (EventViewSet, EventListView, MakeDirectEndpoint,
                    MakeEmbededEndpoint, MakeEvent, MakeFields, MakeFilter, MakeFooter,
                    EventDeleteView, EventUpdateView)
from django.contrib.auth.decorators import login_required

app_name = 'events'

urlpatterns = [
    path('jira-callback/', EventViewSet.as_view(), name='jira-callback'),
    path('events/', login_required(EventListView.as_view()), name='events'),
    path('make_eventdirect/',
         login_required(MakeDirectEndpoint.as_view()), name='make_eventdirect'),
    path('make_eventembed/', login_required(MakeEmbededEndpoint.as_view()),
         name='make_eventembed'),
    path('make_event/', login_required(MakeEvent.as_view()),
         name='make_event'),
    path('make_fields/', login_required(MakeFields.as_view()),
         name='make_fields'),
    path('make_filter/', login_required(MakeFilter.as_view()),
         name='make_filter'),
    path('make_footer/', login_required(MakeFooter.as_view()),
         name='make_footer'),
    path('events/<int:pk>/delete', login_required(EventDeleteView.as_view()),
         name='del_events'),
    path('events/<int:pk>/update', login_required(EventUpdateView.as_view()),
         name='upd_events'),

]

proj_webhook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_hooks.urls')),
    path('users/', include('app_users.urls', namespace='users_log')),
    path('accounts/', include('app_users.urls')),
]

app_hooks/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from rest_framework.permissions import AllowAny
from .webhook import Service
# from .tasks import process_jira_callback_task
from .models import (Event, Filter, EndpointDirect,
                     EmbededFields, EmbededFooter, EndpointEmbeded, MiddlewaresBase)
from django.views.generic import ListView
from app_users.forms import (FilterForm, EndpointDirectForm,
                             EmbededFieldsForm, EmbededFooterForm,
                             EndpointEmbededForm, EventForm, MiddlewareForm)
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic.edit import DeleteView, UpdateView, CreateView


class EventViewSet(APIView):
    permission_classes = [AllowAny]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.service = Service()

    def post(self, request):
        data = request.data
        result = self.service.process_jira_callback(data)
        return Response(result, status=HTTP_200_OK)
        # process_jira_callback_task.apply_async(args=[data])
        # return Response("New task", status=HTTP_200_OK)


class EventListView(ListView):
    model = Event
    template_name = 'app_hooks/events.html'
    context_object_name = 'events'
    paginate_by = 5

    def get_queryset(self):
        return Event.objects.all().order_by('name')


class MakeDirectEndpoint(CreateView):
    model = EndpointDirect
    form_class = EndpointDirectForm
    middleware_form_class = MiddlewareForm
    template_name = 'app_hooks/makedirectevent.html'
    success_url = reverse_lazy('events:make_event')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['direct_form'] = context['form']
            context['middleware_form'] = self.middleware_form_class()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request, f'Direct endpoint {self.object.name} добавлен')

        middleware_type = self.request.POST.get('type')

        # возвращает кортеж (middleware, true/false)
        middleware, created = MiddlewaresBase.objects.get_or_create(
            type=middleware_type)

        if created:
            messages.success(
                self.request, f'Новый middleware {middleware.type} создан')

        if middleware not in self.object.middleware.all():
            self.object.middleware.add(middleware)
            messages.success(
                self.request, f'Middleware {middleware.type} добавлен')

        return response


class MakeEmbededEndpoint(CreateView):
    model = EndpointEmbeded
    form_class = EndpointEmbededForm
    middleware_form_class = MiddlewareForm
    template_name = 'app_hooks/makeembededevent.html'
    success_url = reverse_lazy('events:make_event')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['embeded_form'] = context['form']
            context['middleware_form'] = self.middleware_form_class()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request, f'Embed endpoint {self.object.name} добавлен')

        middleware_type = self.request.POST.get('type')

        # возвращает кортеж (middleware, true/false)
        middleware, created = MiddlewaresBase.objects.get_or_create(
            type=middleware_type)

        if created:
            messages.success(
                self.request, f'Новый middleware {middleware.type} создан')

        if middleware not in self.object.middleware.all():
            self.object.middleware.add(middleware)
            messages.success(
                self.request, f'Middleware {middleware.type} добавлен')

        return response


class MakeEvent(CreateView):
    model = Event
    form_class = EventForm
    template_name = 'app_hooks/makeevent.html'
    success_url = reverse_lazy('events:events')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['event_form'] = context['form']
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'Event {self.object.name} добавлен')
        return response


class MakeFilter(CreateView):
    model = Filter
    form_class = FilterForm
    template_name = 'app_hooks/makefilter.html'
    success_url = reverse_lazy('events:make_event')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['filter_form'] = context['form']
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'Filter {self.object.name} добавлен')
        return response


class MakeFields(CreateView):
    model = EmbededFields
    form_class = EmbededFieldsForm
    template_name = 'app_hooks/makefields.html'
    success_url = reverse_lazy('events:make_eventembed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['embededfields_form'] = context['form']
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'Field {self.object.name} добавлен')
        return response


class MakeFooter(CreateView):
    model = EmbededFooter
    form_class = EmbededFooterForm
    template_name = 'app_hooks/makefooter.html'
    success_url = reverse_lazy('events:make_eventembed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['footer_form'] = context['form']
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'Footer {self.object.text} добавлен')
        return response


class EventDeleteView(DeleteView):
    model = Event
    success_url = reverse_lazy('events:events')

    def get_success_url(self):
        messages.success(self.request, f'Event {self.object.name} удален')
        return super().get_success_url()


class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'app_hooks/update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['event_form'] = context['form']
            context['event_id'] = self.object.id
        return context

    def post(self, request, pk):
        post = get_object_or_404(Event, pk=pk)
        form = EventForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            if 'notpub_button' in request.POST:
                post.draft = False
            elif 'pub_button' in request.POST:
                post.draft = True
            post.save()
            form.save_m2m()
            messages.success(request, f"Event {post.name} обновлен")
            return redirect('events:upd_events', pk=post.pk)
        else:
            form = EventForm(instance=post)
        return render(request, "app_hooks/update.html", {"form": form, "event_id": pk})

    def get_success_url(self):
        return reverse_lazy('events:upd_events', kwargs={'pk': self.object.pk})

app_hooks/templates/app_hooks/events.html
{% extends "app_users/base.html" %} {% block title %} Events app {% endblock %}
{% block all_events %}
<div class="container mt-3">
  <h2>Список созданных Ивентов</h2>
  <p><mark>Всего ивентов: {{ page_obj.paginator.count }}</mark></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Ивенты</th>
        <th>Фильтры</th>
        <th>Эндпоинты</th>
        <th>Статус</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
      <tr>
        <th>{{ forloop.counter }}</th>
        <td>{{ event.name }}</td>
        <td>
          {% for filter in event.filters.all %} {{ filter.name }}
          {% if not forloop.last %}, {% endif %} 
          {% endfor %}
        </td>
        <td>
          {% for endpoint in event.endpoints.all %} {{ endpoint.name }}
          {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>
        <td>
          {% if event.draft %}
            <span class="text-success">ОПУБЛИКОВАН</span>
          {% else %}
            <span class="text-warning">ЧЕРНОВИК</span>
          {% endif %}
        </td>
        <td>
          <button
            type="button"
            class="btn btn-danger"
            data-bs-toggle="modal"
            data-bs-target="#confirmDeleteModal{{ event.id }}"
          >
            Удалить
          </button>
          <div
            class="modal fade"
            id="confirmDeleteModal{{ event.id }}"
            tabindex="-1"
            aria-labelledby="confirmDelete"
            aria-hidden="true"
          >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="confirmDelete">
                    Подтверждение удаления
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <p>
                    Вы уверены, что хотите удалить ивент "{{ event.name }}"?
                  </p>
                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                  >
                    Отмена
                  </button>
                  <form
                    method="post"
                    action="{% url 'events:del_events' pk=event.id %}"
                  >
                    {% csrf_token %}
                    <input
                      type="hidden"
                      name="next"
                      value="{{ request.path }}"
                    />
                    <button type="submit" class="btn btn-danger">
                      Удалить
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </td>
        <td>
          <div>
            <form method="post" action="{% url 'events:upd_events' pk=event.id %}">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-secondary">
                        Изменить
                    </button>
            </form>
        </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="...">
    <ul class="pagination">
      <li
        class="page-item {% if not page_obj.has_previous %}disabled{% endif %}"
      >
        <a
          class="btn btn-outline-warning"
          style="margin-right: 10px"
          href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}"
          tabindex="-1"
          >Назад</a
        >
      </li>
      <li class="page-item disabled">
        <a class="page-link" href="#">{{ page_obj.number }}</a>
      </li>
      <li class="page-item disabled"><a class="page-link" href="#">/</a></li>
      <li class="page-item disabled">
        <a class="page-link" style="margin-right: 10px" href="#"
          >{{page_obj.paginator.num_pages}}</a
        >
      </li>
      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a
          class="btn btn-outline-warning"
          href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}"
          >Вперед</a
        >
      </li>
    </ul>
  </nav>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makedirectevent.html
{% extends "app_users/base.html" %}
{% block title %}Events app {% endblock %}
{% block all_events %}
<div class="col-md-8">
  <br/>
  {% block direct_form_content %}
    {% include "app_users/endpointdirect.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makeembededevent.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-8">
  <br/>
  {% block embeded_form_content %}
  {% include "app_users/endpointembeded.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makeevent.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-5">
  <br/>
  {% block event_form_content %} {% include "app_users/event.html" %} {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makefields.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-12">
  <br/>
  {% block fields_form_content %} {% include "app_users/embededfields.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makefilter.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-12">
  <br/>
  {% block filter_form_content %} {% include "app_users/filter.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makefooter.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-12">
  <br/>
  {% block footer_form_content %} {% include "app_users/embededfooter.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/makemiddleware.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-12">
  <br/>
  {% block middleware_form_content %}
    {% include "app_users/middleware.html" %}
  {% endblock %}
  <br/>
</div>
{% endblock %}

app_hooks/templates/app_hooks/update.html
{% extends "app_users/base.html" %}
{% block title %}Events app{% endblock %}
{% block all_events %}
<div class="col-md-8">
    <br/>
    {% block update_form_content %} {% include "app_users/content_update.html" %}
    {% endblock %}
    <br/>
</div>
{% endblock %}